controller_manager:
  ros__parameters:
    update_rate: 20
    use_sim_time: true

    drive_ctrl:
      type: luna_control/LunaController

    joint_broadcast:
      type: joint_state_broadcaster/JointStateBroadcaster

drive_ctrl:
  ros__parameters:
    publish_rate: 20.0
    base_frame_id: base_link

    publish_limited_velocity: true
    # open_loop: true

    left_back_wheel_names: ['drive_bl']
    left_front_wheel_names: ['drive_fl']
    right_back_wheel_names: ['drive_br']
    right_front_wheel_names: ['drive_fr']

    left_back_pod_names: ['steer_bl']
    left_front_pod_names: ['steer_fl']
    right_back_pod_names: ['steer_br']
    right_front_pod_names: ['steer_fr']

    wheel_radius: 0.2
    wheel_track: 0.531
    wheel_base: 0.508
